--- 
  #Instalando varios pacotes com um comando so
- hosts: all
  handlers:
    - name: restart apache #para o notify
      service:
        name: apache2
        state: restarted
      become: yes
  tasks: 
    - name: 'instala Pacotes'
      apt:
       name: "{{ item }}"
       state: latest
      become: yes #equivalente ao sudo
      with_items:
        - php
        - apache2
        - libapache2-mod-php
        - php-gd
        - php8.1-ssh2
        - php-mcrypt
        - mysql-server-5.7
        - python-mysqldb
        - php-mysql
        
    - name: 'Criando o banco'
      mysql_db:
         name: wordpress_db #nome do banco
         login_user: root
         state: present #criar um bando de dados para deletar absent

# caso de erro no sql
# $ sudo mysql -u root # I had to use "sudo" since is new installation

# mysql> USE mysql;
# mysql> SELECT User, Host, plugin FROM mysql.user;
# $ sudo mysql -u root # I had to use "sudo" since is new installation

# mysql> USE mysql;
# mysql> UPDATE user SET plugin='mysql_native_password' WHERE User='root';
# mysql> FLUSH PRIVILEGES;
# mysql> exit;

# $ sudo service mysql restart

    - name: 'Cria usuario no MySQL'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present
#para verificar user
# sudo mysql -u root
# show databases;
# use wordpress_db;
# show tables; 
# $ mysql -u wordpress_user -p
# show databases; 

#Caso não funcione posteriormente o melhor a fazer é comentar aqui
    - name: 'Baixa o Wordpress'
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /vagrant/ansible/latest.tar.gz #por algum motivo so funciounou de inicio mandando para /vagrant/ansible no mesmo local de console
        mode: 0440 #informa as permissões ao arquivo baixado.
   #Caso não funcione posteriormente o melhor a fazer é comentar aqui
    - name: 'Descompacta o wordpress'
      unarchive:
        src: /vagrant/ansible/latest.tar.gz
        dest: /var/www/
        remote_src: yes
      become: yes
#Caso não funcione posteriormente o melhor a fazer é comentar aqui

    - copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Configura o wp-config com as entradas do banco de dados' #Localizar e modificar
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: '12345'}
      become: yes

    - name: 'Configura Apache para servir o Wordpress'
      copy:
        src: '/vagrant/files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      notify:
        - restart apache #Comando 
      become: yes