#vagrantfile
#criando uma máquina chamada bionic
#Ver os docs no site
#depois mandar vagrant up

# script para as variáveis
$script_mysql = <<-SCRIPT
 apt-get update && \ 
 apt-get install -y mysql-server-5.7 && \
 mysql -e "create user 'phpuser'@'%' identified by 'pass';"

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  #rodando um sctipt (legal rodar partir do github)
  #  config.vm.provision "shell", path: "https://example.com/provisioner.sh"

  #nova "VM" para o BD
  config.vm.define "mysqldb" do |mysql|
    # redirecionar porta, nesse exemplo a máquina virtual server web 80 
    # a principio fora do mysql fica assim: config.vm.network "forwarded_port", guest: 80, host:8080 
    mysql.vm.network "forwarded_port", guest: 80, host:8080 
    #mysql.vm.network "private_network", ip: "192.168.1.1"
    #mysql.vm.network "private_network", type: "dhcp"
    #Com brigde pegando DHCP
    #mysql.vm.network "public_network"
    mysql.vm.network "public_network", ip:"192.168.1.11"
    
    #Um exemplo de comando echo para virtual
    mysql.vm.provision "shell", inline: "echo Hello, World"
    #Script para enviar key pub do ssh 
    mysql.vm.provision "shell", inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
    # instalar pacotes, ver também que ta usando variável de script
    mysql.vm.provision "shell", inline: $script_mysql
    #colocar nova config alterada no windows para virtual
    mysql.vm.provision "shell", inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf/"
    mysql.vm.provision "shell", inline: "service mysql restart"
    
    #criar pasta personalizada compartilhada entre as máquinas
    mysql.vm.synced_folder "./configs", "/configs"
    #desabilita pasta compartilhada, a do exemplo é a padrão
    mysql .vm.synced_folder ".", "/vagrant", disabled: true
  end
  #segunda maquina virtual para server php  
    config.vm.define "phpweb" do |phpweb|
      phpweb.vm.network "forwarded_port", guest: 8888, host:8888
      phpweb.vm.network "public_network", ip:"192.168.1.12"
      
      #Instalando Puppet e chamando para instalar o PHP Server
      phpweb.vm.provision "shell", 
        inline: "apt-get update && apt-get install -y puppet"
      
        #Chamando o Puppet para maquina PHP
        phpweb.vm.provision "puppet" do |puppet|
          puppet.manifests_path = ".configs/manifests"
          puppet.manifests_file = "phpweb.pp"
          end
      

    end

end
